version: "3.8"

services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: postgresdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      timeout: 20s
      retries: 10

  pythonapp:
    build: ./
    container_name: pythonapp
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
