services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    container_name: postgresdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      timeout: 20s
      retries: 10

  pythonapp:
    build: ./ # This assumes your Dockerfile is in the same directory as this compose file
    container_name: pythonapp
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
